version: '3.7'
services:
  template-api-test:
    image: node:18.13.0
    container_name: template-api-test
    volumes:
      - '.:/home/node/app'
    entrypoint: sh /home/node/app/.docker/entrypoint.test.sh
    environment:
      - NODE_ENV=test
      - TEST=$TEST
    user: root
    ports:
      - '3001:3001'
    depends_on:
      - template-db-test
    networks:
      - template-net-test

  template-db-test:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=template-db-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5001:5001'
    networks:
      - template-net-test

networks:
  template-net-test:
    driver: bridge
